apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "modal-operator.fullname" . }}
  labels:
    {{- include "modal-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["modal-operator.io"]
  resources: ["modaljobs", "modalendpoints", "modalfunctions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["modal-operator.io"]
  resources: ["modaljobs/status", "modalendpoints/status", "modalfunctions/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "modal-operator.fullname" . }}
  labels:
    {{- include "modal-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "modal-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "modal-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
