{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "modal-operator.fullname" . }}
  labels:
    {{- include "modal-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "modal-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.interval }}
    path: /metrics
    {{- with .Values.metrics.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
{{- end }}
