{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "modal-operator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "modal-operator.fullname" . }}-webhook-cert
  dnsNames:
  - {{ include "modal-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  - {{ include "modal-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "modal-operator.fullname" . }}-webhook-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "modal-operator.fullname" . }}-webhook-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "modal-operator.fullname" . }}-webhook
  labels:
    {{- include "modal-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "modal-operator.fullname" . }}-webhook-cert
webhooks:
- name: pod-mutator.modal-operator.io
  clientConfig:
    service:
      name: {{ include "modal-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  objectSelector:
    matchExpressions:
    - key: modal-operator.io/workload-type
      operator: In
      values: ["job", "function"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "modal-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modal-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    {{- include "modal-operator.selectorLabels" . | nindent 4 }}
{{- end }}
