apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modalfunctions.modal-operator.io
spec:
  group: modal-operator.io
  scope: Namespaced
  names:
    plural: modalfunctions
    singular: modalfunction
    kind: ModalFunction
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              handler:
                type: string
              cpu:
                type: string
              memory:
                type: string
              gpu:
                type: string
              env:
                type: object
              timeout:
                type: integer
              concurrency:
                type: integer
            required:
            - image
            - handler
          status:
            type: object
            properties:
              phase:
                type: string
              modal_app_id:
                type: string
              function_url:
                type: string
              message:
                type: string
              created_at:
                type: string
              deployed_at:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
