apiVersion: v1
kind: Pod
metadata:
  name: test-gpu-pod
  namespace: modal-system
  annotations:
    modal-operator.io/offload: "true"
spec:
  containers:
  - name: test
    image: nvidia/cuda:11.8-runtime-ubuntu20.04
    command: ["nvidia-smi"]
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
