apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: modal-pytorch-distributed
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            modal-operator.io/offload: "true"
            modal-operator.io/gpu-type: "A100"
        spec:
          containers:
          - name: pytorch
            image: pytorch/pytorch:latest
            command:
            - python
            - -m
            - torch.distributed.launch
            - --nproc_per_node=1
            - --nnodes=2
            - --node_rank=0
            - --master_addr=modal-pytorch-distributed-master-0
            - --master_port=23456
            - /workspace/train.py
            resources:
              requests:
                nvidia.com/gpu: 1
                memory: "4Gi"
              limits:
                nvidia.com/gpu: 1
                memory: "8Gi"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            modal-operator.io/offload: "true"
            modal-operator.io/gpu-type: "A100"
        spec:
          containers:
          - name: pytorch
            image: pytorch/pytorch:latest
            command:
            - python
            - -m
            - torch.distributed.launch
            - --nproc_per_node=1
            - --nnodes=2
            - --node_rank=1
            - --master_addr=modal-pytorch-distributed-master-0
            - --master_port=23456
            - /workspace/train.py
            resources:
              requests:
                nvidia.com/gpu: 1
                memory: "4Gi"
              limits:
                nvidia.com/gpu: 1
                memory: "8Gi"
