replicaCount: 1

image:
  repository: ghcr.io/solanyn/modal-operator
  pullPolicy: IfNotPresent
  tag: "" # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  metricsPort: 8081

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

modal:
  tokenSecret: modal-operator-secret
  tokenIdKey: MODAL_TOKEN_ID
  tokenSecretKey: MODAL_TOKEN_SECRET
  defaultGpuType: "T4"
  environment: "main"

metrics:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
