name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Lint
      run: uv run ruff check . && uv run ruff format --diff .
    
    - name: Test
      run: uv run pytest --cov=mvgpu --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: modal-vgpu-operator:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  e2e:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - uses: actions/checkout@v4
    
    - name: Create kind cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: modal-vgpu-operator
    
    - name: Build and load image
      run: |
        docker build -t modal-vgpu-operator:latest .
        kind load docker-image modal-vgpu-operator:latest --name modal-vgpu-operator
    
    - name: Deploy operator
      run: |
        helm upgrade --install modal-vgpu-operator ./charts/modal-vgpu-operator \
          --namespace modal-system \
          --create-namespace \
          --set image.tag=latest \
          --set testing.mockModal=true \
          --wait
    
    - name: Test GPU pod
      run: |
        kubectl apply -f test/gpu-pod.yaml
        sleep 30
        kubectl get pods -o wide
        kubectl describe pod test-gpu-pod || true
        kubectl describe pod explicit-offload-pod || true
